=== egoist301/-JavaST_2019_july/task4/data/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://www.example.com/greenhouse"
        targetNamespace="http://www.example.com/greenhouse"
        elementFormDefault="qualified">
    <element name="greenhouse">
        <complexType>
            <sequence>
                <element ref="tns:flower" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="flower" type="tns:Flower" abstract="true"/>

    <complexType name="Flower" mixed="true">
        <sequence>
            <element name="name" type="string"/>
            <element name="origin" type="string"/>
            <element name="stem-color" type="tns:Color"/>
            <element name="height" type="positiveInteger"/>
            <element name="temperature" type="tns:Temperature"/>
            <element name="discovery-date" type="date"/>
        </sequence>
        <attribute name="id" type="positiveInteger" use="required"/>
    </complexType>

    <element name="living-flower" substitutionGroup="tns:flower">
        <complexType mixed="true">
            <complexContent>
                <extension base="tns:Flower">
                    <sequence>
                        <element name="soil" type="tns:Soil"/>
                        <element name="multiplying" type="tns:Multiplying"/>
                        <element name="watering" type="positiveInteger"/>
                    </sequence>
                    <attribute name="is-photophilous" type="boolean" default="false"/>
                    <attribute name="is-medicinal" type="boolean" default="false"/>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="artificial-flower" substitutionGroup="tns:flower">
        <complexType mixed="true">
            <complexContent>
                <extension base="tns:Flower">
                    <sequence>
                        <element name="material" type="string"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <simpleType name="Color">
        <restriction base="string">
            <enumeration value="green"/>
            <enumeration value="red"/>
            <enumeration value="yellow"/>
        </restriction>
    </simpleType>

    <simpleType name="Temperature">
        <restriction base="string" >
            <!-- ID??? -->
            <pattern value="(\d{1,3})-(\d{1,3})"/>
        </restriction>
    </simpleType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="ground"/>
            <enumeration value="sod-podzolic"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="seed"/>
            <enumeration value="leaves"/>
            <enumeration value="cuttings"/>
        </restriction>
    </simpleType>
</schema>

=== egoist301/-JavaST_2019_july/task4/web/data/greenhouse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.training.by/greenhouse"
            xsi:schemaLocation="http://www.training.by/greenhouse greenhouse.xsd">

    <living-flower is-medicinal="true" id="1" is-photophilous="true">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>green</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2000-08-27</discovery-date>
        <soil>ground</soil>
        <multiplying>cuttings</multiplying>
        <watering>500</watering>
    </living-flower>

    <artificial-flower id="2">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>yellow</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2019-08-27</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="3">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>red</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2000-08-27</discovery-date>
        <soil>sod-podzolic</soil>
        <multiplying>seed</multiplying>
        <watering>160</watering>
    </living-flower>

    <artificial-flower id="4">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>green</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2019-08-27</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="5" is-photophilous="true">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>red</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2000-08-27</discovery-date>
        <soil>sod-podzolic</soil>
        <multiplying>leaves</multiplying>
        <watering>50</watering>
    </living-flower>

    <artificial-flower id="6">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>yellow</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2019-08-27</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="7" is-medicinal="true">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>red</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2000-08-27</discovery-date>
        <soil>ground</soil>
        <multiplying>leaves</multiplying>
        <watering>160</watering>
    </living-flower>

    <artificial-flower id="8">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>red</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2019-08-27</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="9" is-photophilous="true">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>yellow</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2000-08-27</discovery-date>
        <soil>podzolic</soil>
        <multiplying>cuttings</multiplying>
        <watering>50</watering>
    </living-flower>

    <artificial-flower id="10">
        <name>Роза</name>
        <origin>Беларусь</origin>
        <stem-color>green</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2019-08-27</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="11">
        <name>Sovetus Socialistus</name>
        <origin>Беларусь</origin>
        <stem-color>yellow</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>1998-03-08</discovery-date>
        <soil>ground</soil>
        <multiplying>seed</multiplying>
        <watering>160</watering>
    </living-flower>

    <artificial-flower id="12">
        <name>Anturium</name>
        <origin>Беларусь</origin>
        <stem-color>green</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>1976-02-27</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="13" is-photophilous="true" is-medicinal="true">
        <name>Alstromeria</name>
        <origin>Беларусь</origin>
        <stem-color>red</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>2003-12-10</discovery-date>
        <soil>sod-podzolic</soil>
        <multiplying>seed</multiplying>
        <watering>50</watering>
    </living-flower>

    <artificial-flower id="14">
        <name>Buvardia</name>
        <origin>Беларусь</origin>
        <stem-color>yellow</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>1999-07-07</discovery-date>
        <material>Metal</material>
    </artificial-flower>

    <living-flower id="15">
        <name>Krassula</name>
        <origin>Беларусь</origin>
        <stem-color>red</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>1987-06-26</discovery-date>
        <soil>podzolic</soil>
        <multiplying>cuttings</multiplying>
        <watering>160</watering>
    </living-flower>

    <artificial-flower id="16">
        <name>Eucalypti Baby-Blue</name>
        <origin>Беларусь</origin>
        <stem-color>green</stem-color>
        <height>80</height>
        <temperature>6-16</temperature>
        <discovery-date>1940-03-22</discovery-date>
        <material>Metal</material>
    </artificial-flower>

</greenhouse>

=== egoist301/-JavaST_2019_july/task4/data/greenhouse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.epam.training.by/greenhouse"
       xsi:schemaLocation="http://www.epam.training.by/greenhouse  greenhouse.xsd">
    <flower id="1" is-photophilous="true">
        <name>Роза</name>
        <soil>GROUND</soil>
        <origin>Беларусь</origin>
        <multiplying>CUTTINGS</multiplying>
        <stem-color>Зелёный</stem-color>
        <height>80</height>
        <temperature>16</temperature>
        <date>31.12.12</date>
    </flower>
</greenhouse>
